// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvooedbkmmjoabmkchow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12b29lZGJrbW1qb2FibWtjaG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Nzc2NDMsImV4cCI6MjA3MjI1MzY0M30.WE666qcA0z-i_KjrejBIeY9jBl67B5-qHSk5xLncp2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});